language: java

jdk:
  - openjdk11

pre_install:
  - sudo apt-get update
  - sudo apt-get install ant
  - echo $(ant -version)

install:
  - ant deps

before_script:
  - echo `ant --version`

script:
  - ant test