language: java

jdk:
  - openjdk11

# https://stackoverflow.com/questions/31392245/what-version-of-ant-comes-with-travis-ci
before_install:
  - wget --no-check-certificate https://www.apache.org/dist/ant/binaries/apache-ant-1.10.1-bin.tar.gz
  - tar -xzvf apache-ant-1.10.1-bin.tar.gz
  - export PATH=`pwd`/apache-ant-1.10.1/bin:$PATH
  - echo $(ant -version)
install:
  - ant deps

before_script:
  - echo `ant --version`

script:
  - ant test