language: java
dist: bionic
jdk:
  - openjdk11

before_install:
  - sudo apt-get update
  - sudo apt-get -y install ant
  - echo $(ant -version)

install:
  - ./build.sh

before_script:
  - echo `ant --version`

script:
  - ant test