language: java

jdk:
  - openjdk11

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install ant
  - echo $(ant -version)
  - ant deps

before_script:
  - echo `ant --version`

script:
  - ant test